kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-configs
data:
  cluster_name: "ntnx-k8-mgmt"
  environment: "non-prod"
  cluster_profile: "llm-management"
  nginx_ingress_version: "4.8.3"
  cert_manager_version: "v1.13.5"
  cert_manager_issuer_name: "selfsigned-cluster-issuer"
  milvus_version: "4.1.13"
  milvus_objects_bucket_name: "milvus"
  kyverno_version: "3.1.4"
  weave_gitops_version: "4.0.36"
