kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:a5T4H9jx8I6zcZp1dGoN9ENj4D/aT/aSfuZVYJquDUWHEEp6VepAVQolphuSQmA=,iv:1DmAgSDCLt5818I2X/QmWM15/mbozAQfnBlRa4rGO8U=,tag:iFl+EfmtVvZEjlNWkEO2Sg==,type:str]
    github_user: ENC[AES256_GCM,data:Ej40irKz0SE=,iv:VFgIy4OCNqxQaQbnC/raT3eGubwFQ12iwAs+x6jaex8=,tag:HLPV+uguQDdsMNqpvszrBw==,type:str]
    github_api_token: ENC[AES256_GCM,data:+UdMjDyXUZigYaWzer0n7rHtCj1uUF/DNKLb6tvBmBUGcCiqL1IAdw==,iv:CchF7XLmAqAobzg90WfsHBCzhT9QSj0H7rUXvFsydtM=,tag:ZaRJ1BpXcGNcqYEVu5UmYA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:wGRbN/k=,iv:sFqcbukH+Y2FczPe0b0gPBLUxv1hpJp5KYs48cWKZw8=,tag:ZGi/D4DqIkVIwpYLeMPe2Q==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:4AQTtXbqbnHY,iv:huhHNm9YDRTZLKU9gRA3oIprgpRM0UypK4vBNHrPOCU=,tag:t3NX7xUpE405AB1wVYFrPQ==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:XYYWxUWdHxXKPVV0NA==,iv:wqMCa3PDQ+2L3aIRyD3mr7rz/aqVJDnq+i7fbFconT4=,tag:sy+UhcYcrycKdrrSkpbeLw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:eoibl/s=,iv:2wgPUfEoJ84yjWBxx5xYgLvxtRRnDyCMclq4QwFO294=,tag:fNCgKmZ191sX5x3nGRltxg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:+vS/BEQhpmRF,iv:NLaxlxuh+crX4WIZD/1NS4XS4YgJk4bghRk+mPAX0ew=,tag:Iqjl5bUJfwDwJhcww2w6RA==,type:str]
    objects_host: ENC[AES256_GCM,data:0cSmAFCDLbY1eer/,iv:/z6t1nfGXFliojvYp+TLsc0uI5fsp09OWnMBEHJDKyw=,tag:0PF9bDElV3uAPLDsid1r+Q==,type:str]
    objects_port: ENC[AES256_GCM,data:hCk=,iv:8urIrHg0VeTKeJz3WxITIRgh+xxlaCoj6s3xfOXZOIs=,tag:3z0ayNqKlP2/5yGmI8qKug==,type:str]
    objects_region: ENC[AES256_GCM,data:fQYOfEEPbdrU,iv:IWHfmJFlIBU97ntpiWkOhm4QuP7HNs2LLk7RnTWDc9M=,tag:rh+YrlrFZxFdLTxbBZvGrQ==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:nITte98=,iv:GXc4ZYhoR/CYLLWqCplA3acNrLMPOXVZX0pEYk3slPw=,tag:9/rB1yTRzDXlBp2C1Mrb3A==,type:str]
    objects_access_key: ENC[AES256_GCM,data:/+PvmhQTHPj926TuAoC4HxoK7UDVA87P17tCw55titU=,iv:Z09lfrjpJ9g/qiKNbHto1rQ1j+xhO4ZtczuKFiz/xJI=,tag:C/vrQ6vt2FvpE3rMOiuJKg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:1N7v6DUwxJNY0e2m9/GiC2Y4ACUfdlsqtVksLBk7eNY=,iv:2JVRvo/nfezIMxSlTKTeW7f6V1Rev9npL7HycOvuQ3Q=,tag:jWicx5O/ZL/sg/1PlavVbg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:v39idJZnb5lSZe9EAvYSfv5fu80LAcgazw==,iv:iXA3peDYMVtKKl65VjFXUYbT+vjCD+nfHf7cJ6WdZGU=,tag:Xjsh1Dv5zxEIbeY4zRHXnQ==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:XWW3lycJ9sgsYoaTgGUn,iv:lkdOsqXmCIfqPYw/9I80wyOzzVMbg1n0z5h4A81PsOc=,tag:ukQBWUXbRz0L/G3VibgRdQ==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:sSUy3g8vFTAKBYIwcNvIJb5twywEuA==,iv:xgZvQuDT/8o+tXLfewo17xUlvWOXNAWj3xIILZHz6Yo=,tag:X67bRMd3ViHnT+jzDimg/Q==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:7AsoOBXGG5fkhyvw4d5SDd3oKaYS7w==,iv:6BpLN+gJ8OkYjvJwvj58OiX6NkaSS1WhMbT5q81f0Bk=,tag:1SuttpfPCFPKhhL8XsDJwg==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:Ax5WdD2O6yta5mw+5KJVyDkk6sK6xVBkgG/kE3UQlRjoSjUq8x2bHNTE/vI8Aw2IU8H2YqtDfkQpaFv0,iv:iR+PJfgkYQjh1M0FDMtqvB7ZBVbWvQBCGMqMJx8xKTQ=,tag:ITmuMtS3pbn5/mbxZ64AGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6vltc6txudat2lzdj7sqc43ylkmh2ytydfa9d0wctm5fnt5hg6sr7lnzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaHZsZmxYVll0Tk9SZXU0
            eFBsSXQxT1d4bFd6RWM0MGNoQlo5b1J0SGo4CmhMaGhNSjFCNjN5eVBYWmpRTXhD
            TStMWkZHK1MrTHNPOG5WMmZ3enZSQWsKLS0tIHp6amkvcklQYkNJYU5qZ0xmQ3Z3
            ajBvMzRTQnhBNUdDbXhrdmExa0F2TmMKTCyu3UNbNbHpeZ4OMt0d98KBofFxiLS6
            u7FDJKqmm+dfNpca3jDp5Qfit+6hx7FDUoSiuf1JfTjUoryEzR3AkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T13:23:20Z"
    mac: ENC[AES256_GCM,data:7j0ri428HDcMgy26LgGk+ClkVkpUqnR79fMQxdw9kpdBWuT7KRzZBlFmX4JH8ywCVF49FnGg3GdKUHXJUtbsdW+TpMFGBtIFJhXnXYOZqKlVZEFOOcXxcz/Li6WSW/TsJ1Yu+ceC/B41zuQ1G7tpXK5oyjw7SUk54QNbg0cDDHQ=,iv:EcJwiN3el4zxgOj2jhNSXs7tatpwGH88kYRt2qPOXZ8=,tag:nql7BR52by8N+r0uBqaDIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
